os:
- osx
python:
- 2.7
install:
- brew update
- brew install qt5 python
- wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz
- wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.tar.gz
script:
- echo "Hello OSX!"
- echo "New Build!"