os:
- osx
python:
- 2.7
install:
- brew update
- brew install qt55 python
- brew link --force qt55

- wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz
- wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.tar.gz

- tar xvzf sip-4.17.tar.gz
- cd sip-4.17
- python configure.py
- make
- sudo make install

- tar xvzf yQt-gpl-5.5.1.tar.gz
- cd yQt-gpl-5.5.1
- python configure.py
- make
- sudo make install

script:
- echo "Hello OSX!"
- echo "New Build!"